// sim prints the economics tables in docs/SIMULATION.md from the plan's
// parameters and the gas measured on gno v1.2.0. It is deterministic
// arithmetic, not a Monte Carlo run: the point is to show where the
// break-even lines sit so parameter votes have numbers in front of them.
//
//	go run ./sim > docs/SIMULATION.md
package main

import (
	"fmt"
	"math"
	"os"
	"text/tabwriter"
)

const (
	gnotUSD        = 0.062      // plan §9.3 reference price
	gasSubmit      = 17_700_000 // measured, plain Submit
	gasFinalise    = 27_100_000 // measured, CatchUp of one round
	gasPrice       = 0.001      // ugnot per gas, gnoland-1 minimum
	estimateMargin = 1.25       // the tools' 25% margin
	roundDeposit   = 180_000    // ugnot locked by the first submitter of a round (1.8 kB), refunded on prune
	monthSeconds   = 30 * 24 * 3600.0
	providerShare  = 0.70 // feeSplitProvidersBps
	stakerShare    = 0.15
	treasuryShare  = 0.15
	crankTip       = 0.01
	missSlashBps   = 50
	missCapBps     = 500 // per 7-day epoch
	absenceBps     = 50  // voter penalty per missed ballot
	penaltyCapBps  = 500 // per 30 days
)

func gnot(ugnot float64) string { return fmt.Sprintf("%.2f GNOT", ugnot/1e6) }
func usd(ugnot float64) string  { return fmt.Sprintf("$%.2f", ugnot/1e6*gnotUSD) }

func main() {
	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Println("# Gnoracle economics: break-even tables")
	fmt.Println()
	fmt.Println("Generated by `go run ./sim` from the plan's defaults (Appendix C), the gas")
	fmt.Printf("measured on gno v1.2.0 (Submit %.1fM, finalise %.1fM, %.3f ugnot/gas, %.0f%% estimate margin)\n", gasSubmit/1e6, gasFinalise/1e6, gasPrice, (estimateMargin-1)*100)
	fmt.Printf("and GNOT at $%.3f. Deterministic arithmetic; re-run after a parameter vote.\n\n", gnotUSD)

	feeSubmit := gasSubmit * gasPrice * estimateMargin
	feeFinalise := gasFinalise * gasPrice * estimateMargin

	fmt.Println("## 1. What a provider spends per month, by cadence")
	fmt.Println()
	fmt.Println("Gas only; the storage deposit is refunded when rounds are pruned. Finalising")
	fmt.Println("is shared: the first agent after the window pays it and takes the 1% tip.")
	fmt.Println()
	fmt.Fprintln(w, "| interval\trounds/month\tsubmit gas\tfinalise gas (if this provider cranks all)\tdeposit float (64 rounds kept) |")
	fmt.Fprintln(w, "|---\t---\t---\t---\t--- |")
	for _, iv := range []float64{60, 300, 900, 3600, 6 * 3600, 24 * 3600} {
		rounds := monthSeconds / iv
		fmt.Fprintf(w, "| %s\t%.0f\t%s (%s)\t%s\t%s |\n", dur(iv), rounds, gnot(rounds*feeSubmit), usd(rounds*feeSubmit), gnot(rounds*feeFinalise), gnot(64*roundDeposit))
	}
	w.Flush()
	fmt.Println()

	fmt.Println("## 2. Break-even subscription price per feed")
	fmt.Println()
	fmt.Println("The subscription price per 30 days that pays every provider's gas plus a")
	fmt.Println("margin on stake, given 70% of subscriptions reach the round pools. Stake")
	fmt.Println("margin: the annual return a provider wants on the 10,000 GNOT floor.")
	fmt.Println()
	fmt.Fprintln(w, "| interval\tproviders\tgas/month (all)\tprice for gas only\tprice at 5%/yr on stake\tprice at 15%/yr on stake |")
	fmt.Fprintln(w, "|---\t---\t---\t---\t---\t--- |")
	for _, iv := range []float64{300, 3600, 24 * 3600} {
		for _, n := range []float64{3, 5, 7} {
			rounds := monthSeconds / iv
			gas := n*rounds*feeSubmit + rounds*feeFinalise
			stake := n * 10_000e6
			p0 := gas / providerShare
			p5 := (gas + stake*0.05/12) / providerShare
			p15 := (gas + stake*0.15/12) / providerShare
			fmt.Fprintf(w, "| %s\t%.0f\t%s\t%s (%s)\t%s (%s)\t%s (%s) |\n", dur(iv), n, gnot(gas), gnot(p0), usd(p0), gnot(p5), usd(p5), gnot(p15), usd(p15))
		}
	}
	w.Flush()
	fmt.Println()
	fmt.Println("Reading: the 1,000 GNOT default subscription (about $62) covers an hourly")
	fmt.Println("feed with 5 providers at a 5% stake return; a 5-minute feed needs several")
	fmt.Println("sponsors or a higher price; a one-minute feed is not viable at mainnet gas")
	fmt.Println("prices and should be built as a Gnoswap-TWAP `qeval` read instead.")
	fmt.Println()

	fmt.Println("## 3. Where a subscription goes")
	fmt.Println()
	fmt.Fprintln(w, "| subscription\tproviders (70%)\tstakers (15%)\ttreasury (15%)\tcranker tips (1% of pools) |")
	fmt.Fprintln(w, "|---\t---\t---\t---\t--- |")
	for _, sub := range []float64{100e6, 1000e6, 5000e6} {
		fmt.Fprintf(w, "| %s\t%s\t%s\t%s\t%s |\n", gnot(sub), gnot(sub*providerShare*(1-crankTip)), gnot(sub*stakerShare), gnot(sub*treasuryShare), gnot(sub*providerShare*crankTip))
	}
	w.Flush()
	fmt.Println()

	fmt.Println("## 4. Miss penalties against stake")
	fmt.Println()
	fmt.Println("0.5% per missed round on a funded feed, capped at 5% per 7-day epoch; three")
	fmt.Println("consecutive misses jail (no more misses accrue while jailed).")
	fmt.Println()
	fmt.Fprintln(w, "| stake\tone miss\tthree misses (then jailed)\tweekly cap |")
	fmt.Fprintln(w, "|---\t---\t---\t--- |")
	for _, st := range []float64{10_000e6, 25_000e6, 100_000e6} {
		one := st * missSlashBps / 10_000
		fmt.Fprintf(w, "| %s\t%s (%s)\t%s\t%s |\n", gnot(st), gnot(one), usd(one), gnot(math.Min(3*one, st*missCapBps/10_000)), gnot(st*missCapBps/10_000))
	}
	w.Flush()
	fmt.Println()

	fmt.Println("## 5. A member's voting exposure")
	fmt.Println()
	fmt.Println("0.5% of stake per ballot missed or voted against the outcome, 0.05% for an")
	fmt.Println("abstention, capped at 5% per 30 days. Expected loss for a member who")
	fmt.Println("misses a share of the month's ballots.")
	fmt.Println()
	fmt.Fprintln(w, "| ballots/month\tmisses 10%\tmisses 50%\tmisses all\tcap |")
	fmt.Fprintln(w, "|---\t---\t---\t---\t--- |")
	for _, n := range []float64{1, 4, 12, 30} {
		f := func(share float64) string {
			loss := math.Min(n*share*absenceBps, penaltyCapBps)
			return fmt.Sprintf("%.2f%%", loss/100)
		}
		fmt.Fprintf(w, "| %.0f\t%s\t%s\t%s\t%.1f%% |\n", n, f(0.1), f(0.5), f(1), penaltyCapBps/100.0)
	}
	w.Flush()
	fmt.Println()
	fmt.Println("Reading: at more than ten ballots a month an absent member hits the cap;")
	fmt.Println("the reminders (24 h and 2 h) and the CLI's saved salts exist so that an")
	fmt.Println("attentive member never pays. A member who always abstains pays a tenth.")
	fmt.Println()

	fmt.Println("## 6. Dispute bonds")
	fmt.Println()
	fmt.Println("Bond = max(2,500 GNOT, 10% of the feed's active stake), doubling for repeat")
	fmt.Println("disputes within 7 days (up to 16x). On UPHOLD the bond is forfeited 50% to")
	fmt.Println("the providers, 30% to coherent voters, 20% to the treasury; on OVERTURN the")
	fmt.Println("disputer gets the bond back plus 50% of the slash.")
	fmt.Println()
	fmt.Fprintln(w, "| active stake\tbond\tminor slash (5%) to disputer\tmajor slash (100%) to disputer |")
	fmt.Fprintln(w, "|---\t---\t---\t--- |")
	for _, st := range []float64{30_000e6, 50_000e6, 250_000e6} {
		bond := math.Max(2_500e6, st*0.10)
		fmt.Fprintf(w, "| %s\t%s (%s)\t%s\t%s |\n", gnot(st), gnot(bond), usd(bond), gnot(st/5*0.05*0.5), gnot(st/5*1.0*0.5))
	}
	w.Flush()
	fmt.Println()
	fmt.Println("(one provider of five at fault; the slash lands on the providers found wrong)")
	fmt.Println()
	fmt.Println("## 7. What this does not cover")
	fmt.Println()
	fmt.Println("Price impact of PYTH emissions, sponsor churn, and adversarial voting")
	fmt.Println("cartels are plan §9 and §10 material; a stochastic soak with real gas on")
	fmt.Println("pearl-1 (M6) replaces these tables with observed numbers.")
}

func dur(s float64) string {
	switch {
	case s >= 86400:
		return fmt.Sprintf("%.0f d", s/86400)
	case s >= 3600:
		return fmt.Sprintf("%.0f h", s/3600)
	}
	return fmt.Sprintf("%.0f min", s/60)
}
