#!/usr/bin/env python3
"""Regenerate the plan's Appendix A (entry points), B (events) and C
(parameters) from the realm sources, so the design document cannot drift
from the code. `--check` exits 1 when the document is stale (CI runs it)."""
import re, sys, os, glob

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PLAN = os.path.join(ROOT, "docs", "IMPLEMENTATION_PLAN.md")
REALMS = [("core", "gno.land/r/clockwork/gnoracle/core"), ("dao", "gno.land/r/clockwork/gnoracle/dao"),
          ("kourt", "gno.land/r/clockwork/gnoracle/kourt"), ("token", "gno.land/r/clockwork/gnoracle/token")]
IMPLS = {"core": "gno.land/r/clockwork/gnoracle/core/impl/v1", "dao": "gno.land/r/clockwork/gnoracle/dao/impl/v1",
         "kourt": "gno.land/r/clockwork/gnoracle/kourt/impl/kourtv3"}
UNITS = {"gnot": 1_000_000, "pyth": 1_000_000}


def sources(dirpath):
    for f in sorted(glob.glob(os.path.join(ROOT, dirpath, "*.gno"))):
        if f.endswith("_test.gno") or f.endswith("_filetest.gno"):
            continue
        yield f, open(f).read()


def split_args(s):
    """Split a Go argument list on top-level commas."""
    out, depth, cur, q = [], 0, "", None
    for ch in s:
        if q:
            cur += ch
            if ch == q:
                q = None
            continue
        if ch in "\"'`":
            q = ch
            cur += ch
        elif ch in "([{":
            depth += 1
            cur += ch
        elif ch in ")]}":
            depth -= 1
            cur += ch
        elif ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def call_args(text, start):
    """Return the argument text of the call whose '(' is at start."""
    depth, i, q = 0, start, None
    while i < len(text):
        ch = text[i]
        if q:
            if ch == "\\":
                i += 2
                continue
            if ch == q:
                q = None
        elif ch in "\"`":
            q = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return text[start + 1:i]
        i += 1
    return ""


def entry_points(dirpath):
    crossing, views = [], []
    for f, text in sources(dirpath):
        for m in re.finditer(r"^func ([A-Z]\w*)\((.*?)\)\s*([^{\n]*)\{", text, re.M):
            name, params, ret = m.group(1), m.group(2), m.group(3).strip()
            sig = f"{name}({params})" + (f" {ret}" if ret else "")
            if params.startswith("cur realm"):
                crossing.append(sig)
            else:
                views.append(sig)
    return crossing, views


def events(dirpaths):
    found = {}
    for d in dirpaths:
        for f, text in sources(d):
            for m in re.finditer(r"\b[eE]mit\(", text):
                args = split_args(call_args(text, m.end() - 1))
                if not args or not args[0].startswith('"'):
                    continue
                name = args[0].strip('"')
                keys = []
                for k in args[1::2]:
                    keys.append(k.strip('"') if k.startswith('"') else f"<{k}>")
                found.setdefault(name, set()).add(tuple(keys))
    return found


def params(dirpath):
    rows = []
    for f, text in sources(dirpath):
        for m in re.finditer(r'def\("(\w+)", "([^"]*)", ([^,]+), ([^,]+), ([^,]+), (\d+)\)', text):
            name, doc, dflt, lo, hi, chg = m.groups()
            ev = lambda e: eval(e.replace("_", ""), {"__builtins__": {}}, UNITS)
            rows.append((name, doc, ev(dflt), ev(lo), ev(hi), int(chg)))
        for m in re.finditer(r'DefineString\("(\w+)", "([^"]*)", ([^)]+)\)', text):
            name, doc, dflt = m.groups()
            rows.append((name, doc, dflt.strip(), "", "", "text"))
    return rows


def human(v):
    if v == "" or isinstance(v, str):
        return str(v)
    v = int(v)
    if v >= 1_000_000 and v % 1_000_000 == 0 and v >= 100_000_000:
        return f"{v // 1_000_000:,} GNOT/PYTH ({v})"
    if v >= 3600 and v % 3600 == 0:
        if v % 86400 == 0:
            return f"{v // 86400} d ({v} s)"
        return f"{v // 3600} h ({v} s)"
    return f"{v:,}"


def build():
    out = []
    out.append("## Appendix A. Public API (generated from the sources)\n\n")
    out.append("Generated by `scripts/gen-appendices.py`; edit the realms, not this section. "
               "Crossing functions take `cur realm` and are called with `cross(cur)`; the others are free views "
               "(`vm/qeval`). The behaviour behind each entry point lives in the live implementation realm.\n\n")
    for short, d in REALMS:
        crossing, views = entry_points(d)
        out.append(f"### `{d}`\n\n```go\n")
        for s in crossing:
            out.append(f"func {s}\n")
        out.append("```\n\nViews:\n\n```go\n")
        for s in views:
            out.append(f"func {s}\n")
        out.append("```\n\n")
    out.append("## Appendix B. Events (generated from the sources)\n\n")
    out.append("Every `chain.Emit` in the permanent realms and their implementations, with attribute keys in "
               "emission order (`<expr>` marks a computed key). The bot announces a configurable subset "
               "(`bot.DefaultEvents`).\n\n")
    for short, d in REALMS:
        dirs = [d] + ([IMPLS[short]] if short in IMPLS else [])
        ev = events(dirs)
        if not ev:
            continue
        out.append(f"### `{d}`\n\n| event | attributes |\n|---|---|\n")
        for name in sorted(ev):
            variants = sorted(ev[name])
            out.append(f"| `{name}` | " + " / ".join(", ".join(f"`{k}`" for k in v) if v else "(none)" for v in variants) + " |\n")
        out.append("\n")
    out.append("## Appendix C. Parameter registry (generated from the sources)\n\n")
    out.append("Defaults, bounds and the per-call change limit (`MaxChangeBps`, 5000 = at most 50% per change; the "
               "bounds themselves and one-unit steps are always allowed). A parameter changes at most once per "
               "block height. Amounts are ugnot (PYTH base units on the DAO), times are seconds.\n\n")
    for short, d in [("core", REALMS[0][1]), ("dao", REALMS[1][1])]:
        out.append(f"### `{d}`\n\n| name | default | min | max | change | what |\n|---|---|---|---|---|---|\n")
        for name, doc, dflt, lo, hi, chg in params(d):
            out.append(f"| `{name}` | {human(dflt)} | {human(lo)} | {human(hi)} | {chg} | {doc} |\n")
        out.append("\n")
    return "".join(out)


def main():
    text = open(PLAN).read()
    a = text.index("## Appendix A")
    d = text.index("## Appendix D")
    new = text[:a] + build() + text[d:]
    if "--check" in sys.argv:
        if new != text:
            print("docs/IMPLEMENTATION_PLAN.md appendices are stale: run scripts/gen-appendices.py")
            sys.exit(1)
        print("appendices current")
        return
    open(PLAN, "w").write(new)
    print("appendices regenerated")


if __name__ == "__main__":
    main()
